(function(g){var window=this;'use strict';var I2=function(a){a.publish("cardstatechange",a.Ll()&&a.Zp()?1:0)},J2=function(a,b){var c=g.Sa(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(a==null)return;a=a[d[c]]}return a},Oeb=function(a){var b=g.Lm(a);
a=g.Om(a);return new g.zm(b.x,b.y,a.width,a.height)},Peb=function(a,b,c){var d=d===void 0?{}:d;
var e;return e=g.Ns(a,b,function(){g.Os(e);c.apply(a,arguments)},d)},M2=function(a){a=g.Wa(a);
delete K2[a];g.Pg(K2)&&L2&&L2.stop()},Reb=function(){L2||(L2=new g.qp(function(){Qeb()},20));
var a=L2;a.isActive()||a.start()},Qeb=function(){var a=g.Za();
g.Fg(K2,function(b){Seb(b,a)});
g.Pg(K2)||Reb()},N2=function(a,b,c,d){g.Dp.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.B=a;this.T=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.K=0;this.D=null},Seb=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);a.progress>1&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;Teb(a,a.progress);a.progress==1?(a.j=0,M2(a),a.onFinish(),a.Ls()):a.isPlaying()&&a.zO()},Teb=function(a,b){typeof a.G==="function"&&(b=a.G(b));
a.coords=Array(a.B.length);for(var c=0;c<a.B.length;c++)a.coords[c]=(a.T[c]-a.B[c])*b+a.B[c]},Ueb=function(a,b){g.Zh.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.j},O2=function(a,b,c,d,e){N2.call(this,b,c,d,e);
this.element=a},Veb=function(a,b,c,d,e){if(b.length!=2||c.length!=2)throw Error("Start and end points must be 2D");
O2.call(this,a,b,c,d,e)},Web=function(a){return Math.pow(a,3)},Xeb=function(a){return 3*a*a-2*a*a*a},Yeb=function(a){g.O.call(this);
this.B=a||window;this.j=[]},P2=function(a){return a.baseUrl||null},Q2=function(a,b){return g.yn(g.Nl(a,b),function(c){return!!c})},Zeb=function(a,b,c){function d(ma){var X=ma.hovercardButton;
if(!X)return null;X=X.subscribeButtonRenderer;if(!X)return null;var Q=f(X.unsubscribedButtonText),Y=f(X.subscribedButtonText);if(X.subscribed){var v=f(X.subscriberCountWithUnsubscribeText);var T=f(X.subscriberCountText)}else v=f(X.subscriberCountText),T=f(X.subscriberCountWithSubscribeText);var $a=null;if(ma.signinEndpoint){$a=J2(ma,"signinEndpoint","webNavigationEndpointData","url");if(!$a){var vb,nb;$a=(nb=g.R((vb=X.signInEndpoint)==null?void 0:vb.commandMetadata,g.B1))==null?void 0:nb.url}if(!$a)return null}return Q&&
(Y||$a)?{subscribed:X.subscribed,subscribeText:Q,subscribeCount:v,unsubscribeText:Y,unsubscribeCount:T,enabled:X.enabled,signinUrl:$a,classic:ma.useClassicSubscribeButton}:null}
function e(ma){if(ma){var X=[],Q=ma.videoId;Q&&X.push("v="+Q);(Q=ma.playlistId)&&X.push("list="+Q);(ma=ma.startTimeSeconds)&&X.push("t="+ma);return"/watch?"+X.join("&")}}
function f(ma){if(!ma)return null;var X=ma.simpleText;return X?X:ma.runs?g.Nl(ma.runs,function(Q){return Q.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,t=null,u=null,y=!1,A=null,C=null,E=null,H=null,L=null,M=null;if(h==="VIDEO")g.R(l,g.gy)?m=g.R(l,g.gy).url:(M=g.R(l,g.dR),m=e(M)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p=p.style==="LIVE"):r=f(b.videoDuration);else if(h==="PLAYLIST")g.R(l,g.gy)?m=g.R(l,g.gy).url:(M=g.R(l,g.dR),m=e(M)),n=!1,q=a,t=f(b.playlistLength);else if(h===
"CHANNEL"){if(y=J2(l,"browseEndpoint","browseId"))u=y,m="/channel/"+u;n=!1;q="new";(y=!!b.isSubscribe)?A=d(b):C=f(b.subscribersText)}else h==="WEBSITE"?((E=J2(l,"urlEndpoint","url"))&&(m=E),n=!0,q="new",E=b.icon.thumbnails[0].url):h==="CREATOR_MERCHANDISE"&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(L=f(b.additionalFeesText)),(n=J2(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=J2(b,"title","accessibility","accessibilityData","label");var W=b.endpoint?b.endpoint.clickTrackingParams:
null,V="";if(b.metadata){var ca=f(b.metadata);ca&&(V=ca)}return{id:"element-"+c,type:h,title:f(b.title),metadata:V,callToAction:f(b.callToAction),vY:b.image,iconUrl:E,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,qG:p,playlistLength:t,channelId:u,subscribeButton:A,subscribersText:C,isSubscribe:y,targetUrl:m||null,T$:n,sessionData:W?{itct:W}:null,Bfa:q,HE:a?a:null,
isPlaceholder:b.isPlaceholder,impressionUrls:Q2(b.impressionUrls||[],P2),G$:Q2(b.hovercardShowUrls||[],P2),clickUrls:Q2(l.loggingUrls||[],P2),visualElement:g.Rw(b.trackingParams),productPrice:H,additionalFeesText:L,watchEndpoint:M||null}},$eb=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:Q2(a.impressionUrls||[],P2),elements:Q2(a.elements||[],function(d,e){return Zeb(b,d,e)})};
a.trackingParams&&(c.visualElement=g.Rw(a.trackingParams));return c},afb=function(a){g.YX.call(this,a);
this.C=this.endscreen=null;this.j={};this.G={};this.D=this.B=null;this.T=[];this.X=!0;this.K=0;a=a.U();this.V=g.GP(a)||g.IP(a);this.events=new g.XF(this);g.P(this,this.events);this.events.S(this.player,g.yE("creatorendscreen"),this.onCueRangeEnter);this.events.S(this.player,g.zE("creatorendscreen"),this.onCueRangeExit);this.events.S(this.player,"resize",this.kc);this.events.S(window,"focus",this.yda);this.load();var b=g.nh("STYLE");(g.eh("HEAD")[0]||document.body).appendChild(b);this.addOnDisposeCallback(function(){g.sh(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},bfb=function(a){return a.player.getVideoData().Mf?"current":a.V?"new":"current"},R2=function(a){return a.player.U().playerStyle==="creator-endscreen-editor"},cfb=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.C&&a.C.abort();c={method:"POST",onFinish:function(e){var f=a.C=null;e.status===200&&(e=e.responseText,e.substring(0,3)===")]}"&&(e=e.substring(3),f=JSON.parse(e),f=$eb(f,bfb(a))));S2(a,f)},
urlParams:{v:c},withCredentials:!0};a.V&&(c.urlParams.ptype="embedded");var d=b.Tw;d&&(c.postParams={ad_tracking:d});if(b=g.rMa(b))if(b=g.Sf(b),b=g.Of(b))a.C=g.Qr(b,c)},S2=function(a,b,c){c=c===void 0?!0:c;
a.player.Ze("creatorendscreen");a.B&&(a.B.dispose(),a.B=null,a.D.dispose(),a.D=null);for(var d=g.w(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.G={};a.T.length>0&&(a.T.forEach(function(l){l.dispose()}),a.T.length=0);
a.K=0;if((a.endscreen=b)&&b.elements){c&&dfb(a);c=[];d=new g.wE(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.U().B||(a.B=new g.S({I:"div",N:"ytp-ce-shadow"}),g.jS(a.player,a.B.element,4),a.D=new g.zy(a.B,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=efb(a,e);if(f){a.j[e.id]=f;a.G[e.id]=e;g.jS(a.player,f.element,4);var h=new g.wE(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);ffb(a,f,e)}else g.cx(new g.kt("buildEndscreenElement null",
e))}a.player.df(c);a.kc()}},dfb=function(a){var b=g.Tw(),c=g.Uw();
c&&b&&a.endscreen.visualElement&&g.pr(g.ox)(void 0,c,b,a.endscreen.visualElement)},efb=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={I:"div",Ka:["ytp-ce-element","ytp-ce-video"],Y:{tabindex:"0","aria-label":b.HE||"","aria-hidden":"true"},W:[{I:"div",N:"ytp-ce-element-shadow"},{I:"div",N:"ytp-ce-covering-image",Y:T2(b)},{I:"div",N:"ytp-ce-covering-shadow-top"},{I:"a",N:"ytp-ce-covering-overlay",Y:{href:U2(a,b.targetUrl),tabindex:"-1"},W:[{I:"div",Ka:["ytp-ce-video-title","ytp-webkit-ellipsis"],Y:{dir:g.Hp(b.title||"")},xa:b.title},{I:"div",N:b.qG?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
xa:b.videoDuration||void 0}]}]};c=new g.S(a);break;case "PLAYLIST":a={I:"div",Ka:["ytp-ce-element","ytp-ce-playlist"],Y:{tabindex:"0","aria-label":b.HE||"","aria-hidden":"true"},W:[{I:"div",N:"ytp-ce-element-shadow"},{I:"div",N:"ytp-ce-covering-image",Y:T2(b)},{I:"div",N:"ytp-ce-covering-shadow-top"},{I:"a",N:"ytp-ce-covering-overlay",Y:{href:U2(a,b.targetUrl),tabindex:"-1"},W:[{I:"div",Ka:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],Y:{dir:g.Hp(b.title||"")},xa:b.title},{I:"div",N:"ytp-ce-playlist-count",
W:[{I:"div",N:"ytp-ce-playlist-icon"},{I:"div",N:"ytp-ce-playlist-count-text",xa:b.playlistLength||void 0}]}]}]};c=new g.S(a);break;case "CHANNEL":c={I:"div",Ka:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],Y:{tabindex:"0","aria-label":b.HE||"","aria-hidden":"true"},W:[{I:"div",N:"ytp-ce-element-shadow"},{I:"div",N:"ytp-ce-expanding-overlay",W:[{I:"div",N:"ytp-ce-expanding-overlay-hider"},{I:"div",N:"ytp-ce-expanding-overlay-background"},{I:"div",N:"ytp-ce-expanding-overlay-content",
W:[{I:"div",N:"ytp-ce-expanding-overlay-body",W:[{I:"div",N:"ytp-ce-expanding-overlay-body-padding",W:[{I:"a",Ka:["ytp-ce-channel-title","ytp-ce-link"],Y:{href:U2(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Hp(b.title||"")},xa:b.title},b.subscribeButton?{I:"div",N:"ytp-ce-subscribe-container",W:[{I:"div",N:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{I:"div",N:"ytp-ce-channel-subscribers-text",xa:b.subscribersText}:"",b.metadata?{I:"div",Ka:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],xa:b.metadata}:""]}]}]}]},{I:"div",N:"ytp-ce-expanding-image",Y:T2(b)}]};c=new g.S(c);var d=g.gh(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.yp(d,"ytp-ce-subscribe-button");if(a.player.U().B){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.CY(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player,!1);d.appendChild(e.element);a.T.push(e)}break;case "WEBSITE":a={I:"div",Ka:["ytp-ce-element","ytp-ce-website"],Y:{tabindex:"0","aria-label":b.HE||"","aria-hidden":"true"},W:[{I:"div",N:"ytp-ce-element-shadow"},{I:"div",N:"ytp-ce-expanding-overlay",W:[{I:"div",N:"ytp-ce-expanding-overlay-hider"},{I:"div",N:"ytp-ce-expanding-overlay-background"},{I:"div",N:"ytp-ce-expanding-overlay-content",W:[{I:"div",N:"ytp-ce-expanding-overlay-body",W:[{I:"div",
N:"ytp-ce-expanding-overlay-body-padding",W:[{I:"div",N:"ytp-ce-website-title",Y:{dir:g.Hp(b.title||"")},xa:b.title},{I:"div",N:"ytp-ce-website-metadata",xa:b.metadata},{I:"a",Ka:["ytp-ce-website-goto","ytp-ce-link"],Y:{href:U2(a,b.targetUrl),target:"_blank",tabindex:"-1"},xa:b.callToAction}]}]}]}]},{I:"div",N:"ytp-ce-expanding-image",Y:T2(b)},{I:"div",N:"ytp-ce-expanding-icon",Y:gfb(b.iconUrl)}]};c=new g.S(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={I:"div",N:"ytp-ce-merchandise-price-container",
W:[{I:"div",N:"ytp-ce-merchandise-price",xa:b.productPrice}]},b.additionalFeesText&&c.W.push({I:"div",N:"ytp-ce-merchandise-additional-fees",xa:b.additionalFeesText})),a={I:"div",Ka:["ytp-ce-element","ytp-ce-merchandise"],Y:{tabindex:"0","aria-label":b.HE||"","aria-hidden":"true"},W:[{I:"div",N:"ytp-ce-element-shadow"},{I:"div",N:"ytp-ce-expanding-overlay",W:[{I:"div",N:"ytp-ce-expanding-overlay-hider"},{I:"div",N:"ytp-ce-expanding-overlay-background"},{I:"div",N:"ytp-ce-expanding-overlay-content",
W:[{I:"div",N:"ytp-ce-expanding-overlay-body",W:[{I:"div",N:"ytp-ce-expanding-overlay-body-padding",W:[{I:"div",N:"ytp-ce-merchandise-title",Y:{dir:g.Hp(b.title||"")},xa:b.title},c,{I:"div",N:"ytp-ce-merchandise-metadata",xa:b.metadata},{I:"a",Ka:["ytp-ce-merchandise-goto","ytp-ce-link"],Y:{href:U2(a,b.targetUrl),target:"_blank",tabindex:"-1"},xa:b.callToAction}]}]}]}]},{I:"div",N:"ytp-ce-expanding-image",Y:T2(b)},{I:"div",N:"ytp-ce-merchandise-invideo-cta-container",W:[{I:"div",N:"ytp-ce-merchandise-invideo-cta",
xa:b.callToAction||void 0}]}]},c=new g.S(a)}b.isPlaceholder&&g.yp(c.element,"ytp-ce-placeholder");return c},T2=function(a){if(a.vY)var b=a.vY.thumbnails;
return gfb(b?b[b.length-1].url:null)},gfb=function(a){return a?{style:"background-image: url("+a+")"}:{}},ffb=function(a,b,c){function d(m){m&&(b.listen("blur",function(){m.style.display!="none"&&a.X&&m.focus()}),b.S(m,"focus",f),b.S(m,"blur",h))}
function e(m){a.K+=m;a.K>0?(g.yp(b.element,"ytp-ce-force-expand"),V2(a,c.id,!0)):(g.Ap(b.element,"ytp-ce-force-expand"),g.Ap(b.element,"ytp-ce-element-hover"),V2(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.listen("mouseenter",function(){hfb(a,b,c)});
b.listen("mouseleave",function(){ifb(a,b,c)});
a.player.U().B||b.listen("click",function(){g.yp(b.element,"ytp-ce-element-hover")});
b.listen("click",function(m){jfb(a,c,m)});
b.listen("keypress",function(m){jfb(a,c,m)});
b.listen("focus",function(){hfb(a,b,c)});
b.listen("blur",function(){ifb(a,b,c)});
b.listen("touchstart",function(){hfb(a,b,c)});
var l=g.hh("ytp-ce-expanding-overlay-hider",b.element);l&&b.S(l,"touchstart",function(m){m.stopPropagation();g.Ap(b.element,"ytp-ce-element-hover");g.Ap(b.element,"ytp-ce-force-expand")});
b.listen("keydown",function(m){a.X=m.keyCode===9&&!m.shiftKey});
d(g.hh("ytp-sb-subscribe",b.element));d(g.hh("ytp-sb-unsubscribe",b.element));b.listen("focus",f);b.listen("blur",h)},jfb=function(a,b,c){if(b.targetUrl&&(!c||c.type!=="keypress"||c.keyCode===13)){for(var d=c.target;d&&!g.xp(d,"ytp-ce-element");){g.xp(d,"subscribe-label")&&kfb(a,b);
if(g.xp(d,"ytp-ce-channel-subscribe"))return;d=d.parentElement||null}if(!d||g.xp(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])ifb(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||b.Bfa==="new")kfb(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Sf(U2(a,b.targetUrl)),c=g.Of(c),g.nz(c,void 0,b.sessionData);else{var e=g.VP(a.player.U())||a.player.getVideoData().Mf,f=function(){var h=U2(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=
g.vr(h);e&&n&&(n.v||n.list)?a.player.Lp(n.v,l,n.list,!1,void 0,m||void 0):g.mz(h,l)};
kfb(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},U2=function(a,b){a=a.player.U();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.cQ(a)+b}else return"";return b},hfb=function(a,b,c){g.xp(b.element,"ytp-ce-element-hover")||(c.type==="VIDEO"||c.type==="PLAYLIST"?g.yp(b.element,"ytp-ce-element-hover"):a.player.U().B?(new g.qp(function(){g.yp(b.element,"ytp-ce-element-hover")},200)).start():g.yp(b.element,"ytp-ce-element-hover"),W2(a,c.G$),V2(a,c.id,!0))},ifb=function(a,b,c){g.Ap(b.element,"ytp-ce-element-hover");
g.Ap(b.element,"ytp-ce-force-expand");V2(a,c.id,!1)},V2=function(a,b,c){a.B&&(c?a.D.show():a.D.hide());
for(var d=g.w(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.Cp(a.j[e].element,"ytp-ce-element-shadow-show",c)},W2=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||b.length===0||R2(a))c&&c();else{b=lfb(a,b);var e=0,f=!1,h=new g.qp(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.lv(b[a],d)}},kfb=function(a,b,c){W2(a,b.clickUrls,c);
(a=g.Uw())&&b.T$&&g.zx(a,b.visualElement)},lfb=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(mfb(b[d],c));return a},mfb=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},nfb=function(a){return typeof a==="string"?a:""},X2=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},ofb=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},Y2=function(a){return a.value?a.value:null},Z2=function(a){if(!a)return null;
var b=g.Sf(nfb(a.value));b=g.Of(b);if(!b)return null;var c=X2(a.target,pfb,"current");if(c==null)a=null;else{var d=a.show_link_icon;a=new ofb(b,c,d==="true"||d==="false"?d==="true":!0,a.pause_on_navigation!=null?a.pause_on_navigation:!0)}return a},qfb=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},tfb=function(a){if(!a)return null;
var b=X2(a.type,rfb),c=X2(a.trigger,sfb);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=Z2(a?a:null);return b?new qfb(b,c,a):null},ufb=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},vfb=function(a,b){return g.Tb(a.action,b)},wfb=function(a,b){this.context=a;
this.j=b},xfb=function(a){return a.customMessage?$2("div","iv-card-message",a.customMessage):""},a3=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{I:"div",N:"iv-card-image",Y:{style:a},W:c}},yfb=function(a){if(!a.metaInfo||a.metaInfo.length===0)return"";
var b=[];a=g.w(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push($2("li","",c.value));return{I:"ul",N:"iv-card-meta-info",W:b}},$2=function(a,b,c){b?typeof b==="string"?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Hp(c);return{I:a,Y:b,xa:c}},zfb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.UE&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.UE+");");c.dir=g.Hp(a.customMessage);var d=[{I:"span",xa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({I:"span",N:"iv-card-link-icon"}));return{I:"div",Ka:b,Y:c,W:d}},b3=function(a,b,c,d){if(d){b=g.w(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.zj.click,5)}},Afb=function(a,b){this.merchant=a;
this.price=b},Bfb=function(a){var b;
(b=a)&&!(b=a.length>1?a.charAt(0)==="/"&&a.charAt(1)!=="/":a==="/")&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||b.length<1||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b=b[0]==="com"&&b[1]==="youtube"||b[0]==="be"&&b[1]==="youtu");return b?a.indexOf("/redirect?")===-1:!1},Cfb=function(a,b){return b?b:Bfb(a)?"current":"new"},c3=function(a,b){g.O.call(this);
var c=this;this.element=a;this.context=b;this.qb=!1;this.Ta=new Map;this.Xa=new Map;this.context.J.addEventListener(g.yE("annotations_module"),function(d){(d=c.Ta.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.zE("annotations_module"),function(d){(d=c.Xa.get(d))&&d.apply(c)})},d3=function(a,b,c,d,e,f,h){a.context.j.listen(b,"click",function(l){a.UN(c,d,e,f||[],h||0,l)});
a.context.j.listen(b,"touchstart",function(){a.qb=!1});
a.context.j.listen(b,"touchmove",function(){a.qb=!0})},Dfb=function(a){var b;
return((b=g.R(a,g.gy))==null?0:b.url)?g.R(a,g.gy).url:(a=g.R(a,g.dR))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},e3=function(a,b,c){return{TZ:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
n3:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
xN:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},Efb=function(a,b,c){c3.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.Db=this.Ja=this.Hb=this.C=this.isInitialized=!1;this.cards=[];this.sb=this.V=this.La=this.G=this.Ua=this.j=null;this.oa=[];this.qa=this.T=this.Jf=this.Ga=null;this.K=0;this.Ca=new g.qp(function(){},c.Z.rk?4E3:3E3);
g.P(this,this.Ca);this.fb=new g.qp(function(){});
g.P(this,this.fb);this.Aa=new wfb(c,function(e,f,h,l,m,n){d3(d,e,f,h,l,m,n)});
this.X=new g.S({I:"div",N:"iv-drawer",Y:{id:"iv-drawer"},W:[{I:"div",N:"iv-drawer-header",Y:{"aria-role":"heading"},W:[{I:"span",N:"iv-drawer-header-text"},{I:"button",Ka:["iv-drawer-close-button","ytp-button"],Y:{"aria-label":"Hide cards",tabindex:"0"}}]},{I:"div",N:"iv-drawer-content"}]});g.P(this,this.X);this.D=this.X.element;this.Ya=new g.zy(this.X,330);g.P(this,this.Ya);this.Jb=g.hh("iv-drawer-header-text",this.D);this.B=g.hh("iv-drawer-content",this.D);this.addCueRange(0,c.videoData.lengthSeconds*
1E3,"",function(){d.Hb&&f3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Hb=d.C)&&g3(d)});
this.Oa=new g.XF(this);g.P(this,this.Oa);this.J.addEventListener("videodatachange",this.Iu.bind(this))},Ffb=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){f3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){g3(a)});
var c=b.headerText;g.uh(a.Jb,c);a.V&&a.V.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ga=g.Rw(b.trackingParams);a.T=g.Rw(b.closeTrackingParams);a.Jf=g.Rw(b.iconTrackingParams)},Gfb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.K,d=a.J.U().experiments.bb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.Nx(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,zj:{},cq:null,nk:e.trackingParams?g.Rw(e.trackingParams):null,Jf:f&&f.trackingParams?g.Rw(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
UE:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};h3(a,b)}else{var h;if((h=b.content)==null?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=(e=b.content)==null?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.Nx(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:i3(a,c,b,f),sponsored:!1,zj:e3(f,e,f.command),cq:f.trackingParams?g.Rw(f.trackingParams):null,nk:e.trackingParams?g.Rw(e.trackingParams):null,Jf:l&&l.trackingParams?g.Rw(l.trackingParams):null,imageUrl:j3(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.Nx(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,UE:null,title:f.title?g.Nx(f.title):"",customMessage:f.callToAction?g.Nx(f.callToAction):"",url:g.R(f.command,g.gy).url?Z2({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.R(f.command,g.gy).url}):null,onClickCommand:null};h3(a,b)}else{var m;if((m=b.content)==null?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=(f=b.content)==null?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"collaborator",teaserText:g.Nx(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:i3(a,c,b,e),sponsored:!1,zj:e3(e,f,e.endpoint),cq:e.trackingParams?g.Rw(e.trackingParams):null,nk:f.trackingParams?g.Rw(f.trackingParams):null,Jf:l&&l.trackingParams?g.Rw(l.trackingParams):null,channelId:g.R(e.endpoint,g.sR).browseId,customMessage:e.customText?g.Nx(e.customText):null,profileImageUrl:j3(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.Nx(e.channelName):"",metaInfo:[e.subscriberCountText?g.Nx(e.subscriberCountText):""],url:Z2({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.R(e.endpoint,g.sR).canonicalBaseUrl?g.R(e.endpoint,g.sR).canonicalBaseUrl:"/channel/"+g.R(e.endpoint,g.sR).browseId}),onClickCommand:null};h3(a,b)}else{var n;if((n=b.content)==null?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=(l=b.content)==null?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"playlist",teaserText:g.Nx(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:i3(a,c,b,e),sponsored:!1,zj:e3(e,f,e.action),cq:e.trackingParams?g.Rw(e.trackingParams):null,nk:f.trackingParams?g.Rw(f.trackingParams):null,Jf:l&&l.trackingParams?g.Rw(l.trackingParams):null,vI:j3(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.Nx(e.customMessage):null,playlistVideoCount:g.Nx(e.playlistVideoCount),title:e.playlistTitle?g.Nx(e.playlistTitle):"",metaInfo:[e.channelName?g.Nx(e.channelName):
"",e.videoCountText?g.Nx(e.videoCountText):""],url:Z2({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Dfb(e.action)}),onClickCommand:null};h3(a,b)}else{var p;if((p=b.content)==null?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=(q=b.content)==null?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"video",teaserText:g.Nx(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:i3(a,c,b,e),sponsored:!1,zj:e3(e,f,e.action),cq:e.trackingParams?g.Rw(e.trackingParams):null,nk:f.trackingParams?g.Rw(f.trackingParams):null,Jf:l&&l.trackingParams?g.Rw(l.trackingParams):null,vI:j3(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.Nx(e.lengthString):null,customMessage:e.customMessage?g.Nx(e.customMessage):null,title:e.videoTitle?g.Nx(e.videoTitle):"",metaInfo:[e.channelName?g.Nx(e.channelName):
"",e.viewCountText?g.Nx(e.viewCountText):""],isLiveNow:!!e.badge,url:Z2({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Dfb(e.action)}),onClickCommand:null};h3(a,b)}}}}}a.K++},j3=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||a[e].width===290)return a[e];
((a[e].height||0)<b||(a[e].width||0)<290)&&(c<0||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||(a[e].width||0)>=290)&&(d<0||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[d>=0?d:c]},i3=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},Ifb=function(a,b){if(b=Hfb(a,b))b===a.j&&(a.j=null),a.J.removeCueRange(b.Df.id),g.sh(b.iP),g.Xb(a.cards,b),a.BJ(),k3(a)},f3=function(a,b,c){if(!a.C){a.Ya.show();
a.Ua=new g.qp(function(){g.yp(a.context.J.getRootNode(),g.H_.IV_DRAWER_OPEN)},0);
a.Ua.start();a.Oa.S(a.B,"mousewheel",function(h){a.Ca.start();h.preventDefault();h=h||window.event;var l=0;h.type=="MozMousePixelScroll"?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=h.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.B.scrollTop+=h});
a.C=!0;var d=g.Uw();d&&a.Ga&&a.T&&g.xx(d,[a.Ga,a.T]);b={TRIGGER_TYPE:b};for(var e=g.w(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.T_||(f.T_=!0,Jfb(a.context.logger,f.Df.zj.TZ,b)),d&&g.xx(d,[f.Df.cq]);I2(a.J);c&&(a.G=new g.qp(function(){a.La=a.V;a.sb.focus()},330),a.G.start())}},g3=function(a){a.C&&(a.Ya.hide(),g.Us(a.Oa),g.Ap(a.context.J.getRootNode(),g.H_.IV_DRAWER_OPEN),a.C=!1,I2(a.J),a.G&&a.G.stop(),a.G=new g.qp(function(){a.La&&(a.La.focus(),a.La=null)},330),a.G.start())},Kfb=function(a){g.zp(a.Ib(),
[g.H_.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.jS(a.J,a.D,5);a.nJ();a.V=g.hh("ytp-cards-button",a.J.getRootNode());a.sb=g.hh("iv-drawer-close-button",a.D);a.isInitialized=!0},Lfb=function(a){a.oa.push(g.Ev("iv-teaser-shown",a.d5,a));
a.oa.push(g.Ev("iv-teaser-hidden",a.raa,a));a.oa.push(g.Ev("iv-teaser-clicked",a.c5,a));a.Db=!0},Mfb=function(a,b){var c;
return b.onClickCommand&&((c=g.R(b.onClickCommand,g.ycb))==null?void 0:c.targetId)==="engagement-panel-error-corrections"?(a.qa=b,!0):!1},Nfb=function(a,b){a.qa=b;
var c=a.J.getVideoData();if(!c)return!1;c=g.yQ(c);if(c==null?0:c.markersMap)for(var d,e=0;((d=c)==null?void 0:d.markersMap.length)>e;e++){var f=void 0,h=(f=c)==null?void 0:f.markersMap[e];if(h.key==="ERROR_CORRECTION_MARKERS"&&(f=void 0,(h=(f=h.value)==null?void 0:f.markers)&&h.length>0))return d=void 0,b.startMs=((d=g.R(h[0],g.n4a))==null?void 0:d.timeRangeStartMillis)||0,a.qa=null,!0}return!1},h3=function(a,b){if(!Mfb(a,b)||Nfb(a,b)){var c=Ofb(a,b);
if(c){var d={Df:b,iP:c.element,T_:!1};if(b.onClickCommand)a.J.L("web_infocards_teaser_show_logging_fix")&&(a.Db||Lfb(a),Ifb(a,b.id),c=a.findLastIndex(d),g.cc(a.cards,c,0,d));else{a.isInitialized||Kfb(a);Ifb(a,b.id);var e=a.findLastIndex(d);g.cc(a.cards,e,0,d);c.Ha(a.B,e);a.BJ()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.C||(a.j=d,k3(a),Pfb(a,d),f3(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=a.context.J.getCurrentTime()*1E3,c<5E3&&c>b.startMs&&Qfb(a,d),a.addCueRange(b.startMs,
b.startMs+1,b.id,function(){Qfb(a,d)}),k3(a))}}},Ofb=function(a,b){switch(b.type){case "simple":a=a.Aa;
var c=b.displayDomain?{I:"div",N:"iv-card-image-text",xa:b.displayDomain}:void 0;var d=zfb(b);c={I:"div",Ka:["iv-card"],W:[{I:"a",N:"iv-click-target",Y:{href:b.url?Y2(b.url)||"":""},W:[a3(b.imageUrl,c),{I:"div",N:"iv-card-content",W:[$2("h2",void 0,b.title),d]}]}]};c=new g.S(c);b3(a,g.fh("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Aa;c={I:"div",Ka:["iv-card","iv-card-channel"],W:[{I:"a",Ka:["iv-click-target"],Y:{href:Y2(b.url)||"","data-ytid":b.channelId},W:[a3(b.profileImageUrl),
{I:"div",N:"iv-card-content",W:[xfb(b),{I:"h2",N:"iv-card-primary-link",xa:b.title},yfb(b)]}]}]};c=new g.S(c);b3(a,g.fh("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Aa;c={I:"div",Ka:["iv-card","iv-card-playlist"],W:[{I:"a",N:"iv-click-target",Y:{href:Y2(b.url)||""},W:[a3(b.vI,{I:"div",N:"iv-card-image-overlay",W:[{I:"span",N:"iv-card-playlist-video-count",xa:b.playlistVideoCount}]}),{I:"div",N:"iv-card-content",W:[xfb(b),$2("h2","iv-card-primary-link",b.title),yfb(b)]}]}]};
c=new g.S(c);b3(a,g.fh("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Aa;var e=b.offers.length!=0;c=["iv-card"];d="";var f=zfb(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({I:"div",N:"iv-card-offer-price",xa:f.price}),f.merchant&&e.push({I:"div",N:"iv-card-offer-merchant",xa:f.merchant}),f={I:"div",W:e});e=b.url?Y2(b.url)||"":"";c={I:"div",Ka:c,Y:{tabindex:"0"},W:[{I:"a",Ka:["iv-card-image","iv-click-target"],Y:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{I:"div",N:"iv-card-content",W:[b.sponsored?{I:"div",N:"iv-card-sponsored",W:["Sponsored",{I:"div",N:"iv-ad-info-container",W:[{I:"div",N:"iv-ad-info",xa:"{{adInfo}}"},{I:"div",N:"iv-ad-info-icon-container",W:[{I:"div",N:"iv-ad-info-icon"},{I:"div",N:"iv-ad-info-callout"}]}]}]}:"",{I:"a",N:"iv-click-target",Y:{href:e},W:[$2("h2",d,b.title),f]}]}]};c=new g.S(c);d=g.nh("span");g.uh(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.Fd(d,"adInfo");b3(a,g.fh("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Aa;d=b.videoDuration?{I:"span",N:"iv-card-video-duration",xa:b.videoDuration}:void 0;f=b.isLiveNow?{I:"span",Ka:["yt-badge","yt-badge-live"],xa:"LIVE NOW"}:null;e={I:"div",Ka:["iv-card","iv-card-video"],W:[{I:"a",N:"iv-click-target",Y:{href:((c=b.url)==null?void 0:Y2(c))||""},W:[a3(b.vI,d),{I:"div",N:"iv-card-content",W:[xfb(b),$2("h2","iv-card-primary-link",b.title),yfb(b),f]}]}]};c=new g.S(e);b3(a,g.fh("iv-click-target",
c.element),b,b.url);b=c;break;default:return null}return b},Rfb=function(a){if(a.j)return a.j.Df.type==="productListing";
if(a.J.L("enable_wn_infocards")){var b;return!((b=a.cards)==null||!b.length)&&g.Ol(a.cards,function(c){return c.Df.type==="productListing"})}return g.Ol(a.cards,function(c){return c.Df.type==="productListing"})},k3=function(a){g.Cp(a.J.getRootNode(),"ytp-cards-shopping-active",Rfb(a))},Qfb=function(a,b){if(!g.xp(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.Uw(),d=a.j?a.j.Df.Jf:a.Jf;
c&&d&&g.yx(c,[d]);a.j=b;k3(a)}(c=a.isInitialized&&a.Ib().style.display=="none")||(c=a.context.J.getPlayerState(),d=c===0&&a.context.J.getCurrentTime()===0,c=!(c===1||c===3||d));c||b.Df.teaserDurationMs&&a.J.JC(!0,{teaserText:b.Df.teaserText,durationMs:b.Df.teaserDurationMs,onClickCommand:b.Df.onClickCommand});a.fb.isActive()||((!a.C||!a.Ca.isActive()&&a.Ja)&&Pfb(a,b),a.fb.start(910+b.Df.teaserDurationMs))}},Pfb=function(a,b){a.X.Cb?(b=new N2([0,
a.B.scrollTop],[0,b.iP.offsetTop],600,Xeb),a.context.C.listen(b,"animate",function(c){a.B.scrollTop=c.y}),a.context.C.listen(b,"finish",function(c){a.B.scrollTop=c.y}),b.play()):(g.Jx(a.X,!0),a.B.scrollTop=b.iP.offsetTop,g.Jx(a.X,!1))},l3=function(a){return a.j&&a.j.Df?a.j.Df:a.cards[0]&&a.cards[0].Df?a.cards[0].Df:null},Hfb=function(a,b){return g.Tb(a.cards,function(c){return c.Df.id===b})},m3=function(a,b,c){c3.call(this,a,b);
this.annotation=c;this.isActive=!1},Sfb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(Number(b.start_ms),Number(b.end_ms),a.annotation.id,function(){a.show()},function(){a.hide()})},n3=function(a,b,c){m3.call(this,a,b,c);
this.B=null;this.T=!1;this.C=null;this.D=!1;this.j=this.K=this.G=null},Tfb=function(a,b){var c=c===void 0?0:c;
var d=Oeb(b).width;g.Jm(b,d);c=new Veb(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,Web);g.P(a,c);a.context.C.listen(c,"begin",function(){g.Pm(b,!0)});
c.play()},Wfb=function(a,b){if(b.channel_name){var c=a.createElement({I:"div",
Ka:["iv-branding-context-name"],xa:b.channel_name}),d=a.createElement({I:"div",Ka:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.CY(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.J,!1),a.j.Ha(d));var f=a.createElement({I:"div",Ka:["iv-branding-context-subscribe-caret"]}),h=a.createElement({I:"div",Ka:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.Pm(h,!1);var l=a.createElement({I:"div",Ka:["branding-context-container-outer"]});l.appendChild(h);g.Cm(l,"right",b.image_width+"px");g.ph(a.Ib(),l);a.C=new g.qp(function(){Ufb(a,h,l)},500);
g.P(a,a.C);a.context.j.listen(a.Ib(),"mouseover",function(){Vfb(a,h,l,f,b.image_height)});
a.context.j.listen(a.Ib(),"mouseout",function(){a.C.start()})}},Vfb=function(a,b,c,d,e){a.C.stop();
if(!a.D){var f=g.Om(b);a.j||(b.style.width=g.Im(f.width,!0),c.style.width=g.Im(f.width,!0));g.Cm(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Cm(d,"right","1px");a.D=!0;g.Pm(b,!0);a.G=new g.qp(function(){g.yp(this.Ib(),"iv-branding-active")},0,a);
a.G.start()}},Ufb=function(a,b,c){g.Ap(a.Ib(),"iv-branding-active");
a.K=new g.qp(function(){g.Pm(b,!1);a.j||(c.style.width=g.Im(0,!0))},250);
a.K.start();a.D=!1},Xfb=function(a,b,c,d,e,f,h){this.j=a;
this.C=b;this.Z=c;this.videoData=d;this.logger=e;this.J=f;this.B=h},Yfb=function(a,b,c){m3.call(this,a,b,c);
var d=this;this.V=this.isCollapsed=this.X=!1;this.K=5E3;this.B=this.C=this.j=this.D=null;this.T=this.createElement({I:"div",Ka:["iv-promo-contents"]});this.G=new g.qp(function(){d.j.setAttribute("aria-hidden","true");g.Pm(d.C,!1);g.Pm(d.B,!0)},700,this);
g.P(this,this.G)},agb=function(a,b,c){c.stopPropagation();
Zfb(a);$fb(a,b);a.j.focus()},bgb=function(a){a.isCollapsed||a.V||a.D||(g.yp(a.Ib(),"iv-promo-collapsed"),a.isCollapsed=!0,a.G.start())},Zfb=function(a){a.G.stop();
a.isCollapsed&&(g.Bp(a.Ib(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Pm(a.B,!1),g.Pm(a.C,!0))},$fb=function(a,b){a.D||(a.D=g.Ki(function(){cgb(this);
bgb(this)},b,a))},cgb=function(a){a.D&&(g.Na.clearTimeout(a.D),a.D=null)},dgb=function(a){this.J=a},Jfb=function(a,b,c){b&&(c?o3(a,b.map(function(d){return g.Uo(d,c)})):o3(a,b))},o3=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.w(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.lv(m,f);d&&(e++,d!==0&&a.J.sendVideoStatsEngageEvent(d,f))},egb=function(a){g.YX.call(this,a);
var b=this;this.oa=this.V=!1;this.loadNumber=0;this.K={};this.logger=new dgb(this.player);this.D=new g.XF(this);this.G=this.T=null;this.events=new g.XF(this);this.qh=this.X=this.j=null;this.qa=[];g.P(this,this.D);this.D.S(this.player,"onVideoAreaChange",function(){b.publish("onVideoAreaChange")});
this.D.S(this.player,"onHideControls",function(){b.publish("onHideControls")});
this.D.S(this.player,"onShowControls",function(){b.publish("onShowControls")});
this.D.S(this.player,"resize",function(d){b.publish("resize",d)});
this.D.S(this.player,"presentingplayerstatechange",function(d){b.publish("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.e5,this);this.subscribe("resize",this.nM,this);this.player.U().Ja.subscribe("vast_info_card_add",this.l1,this);g.P(this,this.events);this.Aa=this.createElement({I:"div",N:"video-custom-annotations"});this.B=new g.S({I:"div",Ka:["ytp-player-content","ytp-iv-player-content"]});g.P(this,this.B);g.jS(this.player,this.B.element,4);this.B.hide();this.C=new g.S({I:"div",Ka:["ytp-iv-video-content"]});g.P(this,this.C);a=this.createElement({I:"div",N:"video-annotations"});
a.appendChild(this.Aa);this.C.element.appendChild(a);this.Tv()&&this.load();var c=this.createElement({I:"style"});(g.eh("HEAD")[0]||document.body).appendChild(c);this.addOnDisposeCallback(function(){g.sh(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},fgb=function(a){a=a.createElement({I:"div",
Ka:["annotation","annotation-type-custom"]});g.Pm(a,!1);return a},ggb=function(a,b){b=!b.isCued()&&!g.U(b,1024);
g.Jx(a.B,b);g.Jx(a.C,b)},hgb=function(a,b,c){a.V=!0;
a.G=g.Qr(b,c)},igb=function(a,b){for(var c={},d=g.w(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Ta(e)&&e.nodeType==1){if(c[e.tagName])var f=c[e.tagName];else if(e.tagName==="data"){e.childNodes.length>0&&(f=e.childNodes[0].nodeValue,c[e.tagName]=typeof f==="string"?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&e.tagName==="TEXT"?e.childNodes.length===1&&e.childNodes[0].nodeType===3?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(igb(a,e))}return c},mgb=function(a){var b=a.player.getVideoData();
if(b.Xa){var c=a.player.U().Ja.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=a.loadNumber;f=b.videoId;a.loaded&&a.loadNumber===e&&a.player.getVideoData().videoId===f&&(h=g.Fr(h)&&h.responseXML?h.responseXML:null)&&jgb(a,h)}};
g.tt()&&(d.onFinish=kgb(a,d.onFinish));d.postParams={ic_only:"1"};lgb(d,c);a.V=!0;g.Qr(b.Xa,d)}}},lgb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.GJ&&(a.postParams.ic_coll=b.GJ);b.jP&&(a.postParams.ic_xml=b.jP);b.CN&&(a.postParams.ic_track=b.CN)},ngb=function(a){var b=new g.S({I:"div"});
g.Pm(b.element,!1);var c=new Efb(a.player,b.element,p3(a));g.P(c,b);b.Ha(a.B.element);c.eI();return c},pgb=function(a,b){var c,d;
if(b=(c=b.getWatchNextResponse())==null?void 0:(d=c.cards)==null?void 0:d.cardCollectionRenderer)a.oa=!0,ogb(a,b),b.headerText&&a.qh&&(c=g.Nx(b.headerText),a.qh.setAttribute("title",c))},p3=function(a){if(!a.X){var b=new Yeb(a);
g.P(a,b);var c=new g.Ok(a);g.P(a,c);a.X=new Xfb(b,c,a.player.U(),a.player.getVideoData(),a.logger,a.player,a.Uj)}return a.X},jgb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(d.length<1)&&(d=d[0].getAttribute("itct"))){var e=g.Uw();if(e){var f=g.Tw();f&&g.pr(g.nx)(void 0,e,f,[g.Rw(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=igb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m=typeof h==="string"&&l!=null&&h!=null&&h.match(l)?h:"";var n=X2(f.type,qgb),p=X2(f.style,rgb),q=nfb(f.data),r=q.length!==0?JSON.parse(q):{};var t=f.action;f=tfb;if(t==null)var u=null;else if(g.Sa(t)){l=[];for(var y=g.w(t),A=y.next();!A.done;A=y.next()){var C=f(A.value);
C&&l.push(C)}u=l}else{var E=f(t);u=E?[E]:[]}e=m&&n?new ufb(m,n,p,u,r):null}else e=null}catch(ca){}if(e)if(e.type==="branding"||e.type==="promotion"){f=a;l=e;var H=fgb(f),L=null;switch(l.type){case "branding":if(f.player.U().Gd)break;f.B.element.appendChild(H);L=new n3(H,p3(f),l);break;case "promotion":g.jS(f.player,H,4),L=new Yfb(H,p3(f),l)}L&&L.eI();if(f=L)g.P(a,f),a.K[e.id]=f}else if(e.type==="card"||e.type==="drawer"){a.j||(a.j=ngb(a),g.P(a,a.j));if(e.type==="card"){H=a.j;var M=(c=e)&&c.data&&
c.data.card_type;e=c.data;if(M)switch(f=e.tracking||{},f={TZ:f.impression,click:f.click,close:f.close,n3:f.teaser_impression,xN:f.teaser_click},l=e.tracking_params||{},L=null,M){case "collaborator":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,zj:f,cq:l.card?g.Rw(l.card):null,nk:l.teaser?g.Rw(l.teaser):null,Jf:l.icon?g.Rw(l.icon):
null,channelId:e.channel_id,customMessage:e.custom_message?e.custom_message:null,profileImageUrl:e.image_url,title:e.title,metaInfo:e.meta_info,url:Z2({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};h3(H,c);break;case "playlist":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,zj:f,
cq:l.card?g.Rw(l.card):null,nk:l.teaser?g.Rw(l.teaser):null,Jf:l.icon?g.Rw(l.icon):null,vI:e.image_url,playlistVideoCount:e.playlist_video_count,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,url:Z2({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};h3(H,c);break;case "productListing":e.signin_url&&(L=Z2({target:"current",value:e.signin_url}));M=[];for(var W=e.offers||[],V=0;V<W.length;V++)M.push(new Afb(g.lg(W[V].merchant),
g.lg(W[V].price)));c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,zj:f,cq:l.card?g.Rw(l.card):null,nk:l.teaser?g.Rw(l.teaser):null,Jf:l.icon?g.Rw(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,UE:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?
e.custom_message:null,url:Z2({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),Iqa:L,Hqa:e.signin_title?e.signin_title:void 0,Gqa:e.signin_message?e.signin_message:void 0,offers:M,onClickCommand:null};h3(H,c);break;case "simple":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,zj:f,cq:l.card?g.Rw(l.card):
null,nk:l.teaser?g.Rw(l.teaser):null,Jf:l.icon?g.Rw(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,UE:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?e.custom_message:null,url:Z2({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};h3(H,c);break;case "video":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,
startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,zj:f,cq:l.card?g.Rw(l.card):null,nk:l.teaser?g.Rw(l.teaser):null,Jf:l.icon?g.Rw(l.icon):null,vI:e.image_url,videoDuration:e.video_duration||null,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,isLiveNow:!!e.is_live_now,url:Z2({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null},h3(H,c)}}else Ffb(a.j,e);c=!0}}c&&
(I2(a.player),a.nM())},ogb=function(a,b){var c=!1;
a.j||(a.j=ngb(a),g.P(a,a.j));for(var d=g.w(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(Gfb(a.j,e.cardRenderer),c=!0);if(c){var f;(f=a.player.getVideoData())!=null&&g.zR(f)||(c=a.j,d=b.headerText?g.Nx(b.headerText):"",g.uh(c.Jb,d),c.V&&c.V.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ga=b.trackingParams?g.Rw(b.trackingParams):null,c.T=b.closeButton.infoCardIconRenderer.trackingParams?g.Rw(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.Jf=b.icon.infoCardIconRenderer.trackingParams?g.Rw(b.icon.infoCardIconRenderer.trackingParams):null,a.nM());I2(a.player)}},sgb=function(a,b,c,d,e){if(!a.player.U().Gd){var f=[];
b.navigationEndpoint&&g.R(b.navigationEndpoint,g.sR)&&g.R(b.navigationEndpoint,g.sR).browseId&&f.push(new qfb("openUrl","click",new ofb("/channel/"+g.R(b.navigationEndpoint,g.sR).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.R(b.subscribeButton,
g.tR)){d.channel_id=g.R(b.subscribeButton,g.tR).channelId;var l;b=g.R(b.subscribeButton,g.tR);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.Nx(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.Nx(b.subscriberCountText))):(b.subscriberCountText&&(e=g.Nx(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.Nx(b.subscriberCountWithSubscribeText)));var m,n=((m=g.R((l=b.signInEndpoint)==null?void 0:l.commandMetadata,g.B1))==null?void 0:m.url)||"";l={subscribeText:g.Nx(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.Nx(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new ufb(c,"branding","branding",f,d);l=fgb(a);a.B.element.appendChild(l);f=new n3(l,p3(a),f);f.eI();g.P(f,f);a.K[c]=f}},kgb=function(a,b){return function(){var c=g.Ea.apply(0,arguments);
a.Ia()||a.qa.push(g.jp.bj(function(){b.apply(null,g.x(c))}))}},tgb=function(a){return a==="annotation-editor"||a==="live-dashboard"};
g.cS.prototype.JC=g.da(35,function(a,b){var c=g.kY(this.zb());c&&c.JC(a,b)});
var K2={},L2=null;g.bb(N2,g.Dp);g.k=N2.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||this.j==0)this.progress=0,this.coords=this.B;else if(this.isPlaying())return!1;M2(this);this.startTime=a=g.Za();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.dM();this.Ao("play");this.isPaused()&&this.Ao("resume");this.j=1;var b=g.Wa(this);b in K2||(K2[b]=this);Reb();Seb(this,a);return!0};
g.k.stop=function(a){M2(this);this.j=0;a&&(this.progress=1);Teb(this,this.progress);this.onStop();this.Ls()};
g.k.pause=function(){this.isPlaying()&&(M2(this),this.j=-1,this.Ao("pause"))};
g.k.va=function(){this.j==0||this.stop(!1);this.Ao("destroy");N2.Vf.va.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.zO=function(){this.Ao("animate")};
g.k.Ao=function(a){this.dispatchEvent(new Ueb(a,this))};
g.bb(Ueb,g.Zh);g.bb(O2,N2);O2.prototype.C=function(){};
O2.prototype.zO=function(){this.C();O2.Vf.zO.call(this)};
O2.prototype.Ls=function(){this.C();O2.Vf.Ls.call(this)};
O2.prototype.dM=function(){this.C();O2.Vf.dM.call(this)};
g.bb(Veb,O2);Veb.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.z(Yeb,g.O);g.k=Yeb.prototype;g.k.listen=function(a,b,c,d){c=(0,g.Xa)(c,d||this.B);a=g.Ns(a,b,c);this.j.push(a);return a};
g.k.GG=function(a,b,c,d){c=(0,g.Xa)(c,d||this.B);a=Peb(a,b,c);this.j.push(a);return a};
g.k.Mc=function(a){g.Os(a);g.Xb(this.j,a)};
g.k.removeAll=function(){g.Os(this.j);this.j.length=0};
g.k.va=function(){this.removeAll();g.O.prototype.va.call(this)};g.z(afb,g.YX);g.k=afb.prototype;g.k.load=function(){g.YX.prototype.load.call(this);if(!R2(this)){var a=g.sMa(this.player.getVideoData());a?(a=$eb(a,bfb(this)),S2(this,a,!1)):cfb(this)}};
g.k.unload=function(){S2(this,null);this.C&&(this.C.abort(),this.C=null);g.YX.prototype.unload.call(this)};
g.k.oi=function(a,b){return R2(this)?a==="loadCustomEndscreenRenderer"?(a=$eb(b,"new"),S2(this,a),!0):null:null};
g.k.getOptions=function(){return R2(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.kc=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&a.width!==0&&a.height!==0){var b=this.player.getPlayerSize();if(b&&b.width!==0&&b.height!==0){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<ugb.length;f++){var h=Math.abs(b.width-ugb[f]);if(e===-1||d>=h)e=f,d=h}d=vgb[e];this.B&&g.Cm(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.Nm(e.element,m,f);g.Jm(e.element,n,p);g.Bp(e.element,wgb);m>256||f>256?g.yp(e.element,"ytp-ce-large-round"):m>96||f>96?g.yp(e.element,"ytp-ce-medium-round"):g.yp(e.element,"ytp-ce-small-round");g.Bp(e.element,xgb);m=h.left+h.width/2;h=h.top+l/2;g.yp(e.element,m<=.5&&h<=.5?"ytp-ce-top-left-quad":m>.5&&h<=.5?"ytp-ce-top-right-quad":
m<=.5&&h>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Bp(e.element,vgb);g.yp(e.element,d);(e=g.gh(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Cm(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if(a.getId()==="ytp-ce-in-endscreen")W2(this,this.endscreen.impressionUrls),(a=g.Uw())&&this.endscreen.visualElement&&g.wx(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.G[a];g.yp(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.yp(b,"ytp-ce-shown");W2(this,c.impressionUrls);(b=g.Uw())&&g.wx(b,c.visualElement);this.player.U().T&&this.player.eb("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if(a.getId()!=="ytp-ce-in-endscreen"){a=a.getId().substring(15);var b=this.j[a];g.Ap(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.Ap(b,"ytp-ce-shown");this.player.U().T&&this.player.eb("endscreenelementhidden",a)}};
g.k.yda=function(a){var b=this;a.target===window&&(new g.qp(function(){for(var c=g.w(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.Bp(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var ugb=[346,426,470,506,570,640,853,1280,1920],vgb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),xgb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],wgb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var pfb={Yha:"current",Cka:"new"};var rfb={CLOSE:"close",Ika:"openUrl",SUBSCRIBE:"subscribe"},sfb={Hha:"click",CLOSE:"close",aja:"hidden",zla:"rollOut",Ala:"rollOver",Kla:"shown"};ufb.prototype.le=function(){var a=vfb(this,function(b){return b.type==="openUrl"&&b.url!=null});
return a?a.url:null};
var rgb={Sga:"anchored",G4:"branding",CHANNEL:"channel",Xha:"cta",dja:"highlightText",Qja:"label",PLAYLIST:"playlist",POPUP:"popup",Sla:"speech",SUBSCRIBE:"subscribe",dma:"title",VIDEO:"video",Nma:"website"},qgb={G4:"branding",vha:"card",lia:"drawer",cja:"highlight",hka:"marker",gla:"promotion",TEXT:"text",pna:"widget"};g.z(c3,g.O);g.k=c3.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.wE(a,b,{id:c,namespace:"annotations_module"});d&&this.Ta.set(a,d);e&&this.Xa.set(a,e);this.context.J.df([a],1)};
g.k.eI=function(){this.context.B.subscribe("resize",this.BJ,this)};
g.k.Ib=function(){return this.element};
g.k.UN=function(a,b,c,d,e,f){if(this.qb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.sh(this.Ib())};
g.k.BJ=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=Y2(a);if(f){var h=Cfb(f,a.target),l=function(){a.j&&e.context.J.pauseVideo();var m=e.context.videoData.Mf||!1,n=g.vr(f||"");m&&n&&(n.v||n.list)?e.context.J.Lp(n.v,b,n.list,!1):g.nz(f||"",h==="current"?"_top":void 0,b)};
h==="new"&&(l(),l=null);o3(this.context.logger,c,l,d);Bfb(f)||(c=g.Uw(),d=b.itct,c&&d&&g.zx(c,g.Rw(d)))}};
g.k.va=function(){this.Ta.clear();this.Xa.clear();g.O.prototype.va.call(this)};
g.k.createElement=function(a){a=new g.S(a);g.P(this,a);return a.element};g.z(Efb,c3);g.k=Efb.prototype;g.k.Iu=function(){this.qa&&h3(this,this.qa)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.Om(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.BJ=function(){var a=this.isAvailable();g.Pm(this.Ib(),a);g.Cp(this.context.J.getRootNode(),g.H_.IV_DRAWER_ENABLED,a);I2(this.J)};
g.k.destroy=function(){this.J.JC(!1);try{this.J.getRootNode().removeChild(this.D)}catch(a){}g.Fv(this.oa);g.Us(this.Oa);this.Ua&&this.Ua.dispose();this.G&&this.G.dispose();c3.prototype.destroy.call(this)};
g.k.nJ=function(){var a=this;this.context.j.listen(g.hh("iv-drawer-close-button",this.D),"click",this.j8,this);this.context.j.listen(this.B,"touchend",function(){a.Ca.start()});
this.context.j.listen(this.B,"scroll",this.H8,this);this.context.B.subscribe("onHideControls",function(){a.Ja=!0});
this.context.B.subscribe("onShowControls",function(){a.Ja=!1});
this.context.B.subscribe("onVideoAreaChange",function(){a.Ja=g.xp(a.J.getRootNode(),"ytp-autohide")});
this.oa.push(g.Ev("iv-button-shown",this.qaa,this));this.oa.push(g.Ev("iv-button-hidden",this.paa,this));Lfb(this)};
g.k.findLastIndex=function(a){if(this.cards.length===0)return 0;var b=g.Ub(this.cards,function(c){return a.Df.startMs>c.Df.startMs||a.Df.startMs===c.Df.startMs&&a.Df.timestamp>=c.Df.timestamp?!0:!1});
return b===-1?0:b+1};
g.k.j8=function(){if(this.C){o3(this.context.logger,l3(this).zj.close);var a=g.Uw();a&&this.T&&g.zx(a,this.T);g3(this)}};
g.k.H8=function(){g.Cp(this.D,"iv-drawer-scrolled",this.B.scrollTop>0)};
g.k.qaa=function(){var a=g.Uw(),b=l3(this);b=b?b.Jf:this.Jf;a&&b&&g.xx(a,[b])};
g.k.paa=function(){var a=g.Uw(),b=l3(this);b=b?b.Jf:this.Jf;a&&b&&g.yx(a,[b])};
g.k.d5=function(){var a=l3(this);o3(this.context.logger,a.zj.n3);var b=g.Uw();if(b&&a)if(this.J.L("web_infocards_teaser_show_logging_fix")){var c=[];a.nk&&c.push(a.nk);a.Jf&&c.push(a.Jf);c.length>0&&g.xx(b,c)}else g.xx(b,[a.nk,a.Jf])};
g.k.raa=function(){var a=g.Uw(),b=l3(this);a&&b&&g.yx(a,[b.nk])};
g.k.c5=function(a){var b=l3(this),c=g.Uw();this.j?a?(a=this.context.logger,o3(a,b.zj.xN),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.nk&&g.zx(c,b.nk)):(a=this.context.logger,o3(a,b.zj.xN),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Jf&&g.zx(c,b.Jf)):(a=this.context.logger,o3(a,b.zj.xN),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.Jf&&g.zx(c,this.Jf))};g.z(m3,c3);m3.prototype.eI=function(){c3.prototype.eI.call(this);Sfb(this)};
m3.prototype.show=function(){c3.prototype.show.call(this);var a=g.Uw(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.xx(a,[g.Rw(b.itct)])};
m3.prototype.hide=function(){c3.prototype.hide.call(this);var a=g.Uw(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.yx(a,[g.Rw(b.itct)])};g.z(n3,m3);
n3.prototype.oz=function(){g.yp(this.Ib(),"iv-branding");var a=this.annotation.data;this.B=this.createElement({I:"img",Ka:["branding-img","iv-click-target"],Y:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Pm(this.B,!1);var b=this.createElement({I:"button",Ka:["branding-img-container","ytp-button"]});b.appendChild(this.B);this.Ib().appendChild(b);var c=this.annotation.le();c&&d3(this,b,c,this.annotation.id,a.session_data);this.context.J.L("disable_branding_context")||Wfb(this,
a)};
n3.prototype.show=function(){if(!this.isActive&&(m3.prototype.show.call(this),this.T||(this.oz(),this.T=!0),g.Pm(this.Ib(),!0),this.isActive=!0,this.B)){try{Tfb(this,this.B)}catch(a){}g.yp(this.context.J.getRootNode(),"ytp-branding-shown")}};
n3.prototype.hide=function(){this.isActive&&(m3.prototype.hide.call(this),g.Pm(this.Ib(),!1),this.isActive=!1,g.Ap(this.context.J.getRootNode(),"ytp-branding-shown"))};
n3.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);m3.prototype.destroy.call(this)};g.z(Yfb,m3);g.k=Yfb.prototype;
g.k.oz=function(){var a=this,b=this.annotation.data;if(this.annotation.style==="cta")var c=6;else if(this.annotation.style==="video"||this.annotation.style==="playlist")c=7;this.K=b.collapsedelay_ms||this.K;var d=["iv-promo","iv-promo-inactive"];this.Ib().setAttribute("aria-hidden","true");this.Ib().setAttribute("aria-label","Promotion");this.Ib().tabIndex=0;var e=this.annotation.le(),f=b.image_url;if(f){var h=this.createElement({I:"div",Ka:["iv-promo-img","iv-click-target"]});f=this.createElement({I:"img",
Y:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?(f=this.createElement({I:"span",N:"iv-promo-video-duration",xa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=this.createElement({I:"span",N:"iv-promo-playlist-length",xa:b.playlist_length.toString()}),h.appendChild(f));e&&d3(this,h,e,this.annotation.id,b.session_data,void 0,c)}e?(f=this.createElement({I:"a",N:"iv-promo-txt"}),g.Uf(f,Y2(e)),this.j=f):this.j=this.createElement({I:"div",N:"iv-promo-txt"});switch(this.annotation.style){case "cta":case "website":var l=
this.createElement({I:"p",W:[{I:"strong",xa:b.text_line_1}]});var m=this.createElement({I:"p",W:[{I:"span",N:"iv-promo-link",xa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=this.createElement({I:"button",Ka:["iv-promo-round-expand-icon","ytp-button"]});f=this.createElement({I:"button",Ka:["iv-button","iv-promo-button"],W:[{I:"span",N:"iv-button-content",xa:f}]});var p=this.createElement({I:"div",N:"iv-promo-button-container"});p.appendChild(f);e&&d3(this,
this.Ib(),e,this.annotation.id,b.session_data,void 0,c)}g.yp(this.j,"iv-click-target");e&&d3(this,this.j,e,this.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=this.createElement({I:"p",W:[{I:"span",xa:b.text_line_1}]}),m=this.createElement({I:"p",W:[{I:"strong",xa:b.text_line_2}]}),b.is_live&&(l=m,m=this.createElement({I:"span",Ka:["yt-badge","iv-promo-badge-live"],xa:"LIVE NOW"})),g.yp(this.j,"iv-click-target"),e&&d3(this,this.j,e,this.annotation.id,b.session_data,void 0,
c),d.push("iv-promo-video")}l&&this.j.appendChild(l);m&&this.j.appendChild(m);this.T.appendChild(this.j);p&&this.T.appendChild(p);c=this.createElement({I:"div",N:"iv-promo-actions"});this.B=this.createElement({I:"button",Ka:["iv-promo-expand","ytp-button"]});this.B.title="Expand";this.context.j.listen(this.B,"click",function(q){agb(a,5E3,q)});
c.appendChild(this.B);g.Pm(this.B,!1);this.context.j.listen(this.Ib(),"mouseover",this.k$,this);this.context.j.listen(this.Ib(),"mouseout",this.j$,this);this.context.j.listen(this.Ib(),"touchend",function(q){agb(a,5E3,q)});
this.C=this.createElement({I:"button",Ka:["iv-promo-close","ytp-button"]});this.C.title="Close";this.context.j.listen(this.C,"click",this.annotation.style==="cta"&&b.text_line_3?this.f$:this.e$,this);c.appendChild(this.C);g.zp(this.Ib(),d);h&&(g.ph(this.Ib(),h),n&&h.appendChild(n));g.ph(this.Ib(),this.T);g.ph(this.Ib(),c)};
g.k.show=function(){this.isActive||(m3.prototype.show.call(this),this.X||(this.oz(),this.X=!0),g.Pm(this.Ib(),!0),g.Ki(function(){g.Ap(this.Ib(),"iv-promo-inactive")},100,this),this.Ib().removeAttribute("aria-hidden"),this.isActive=!0,cgb(this),Zfb(this),$fb(this,this.K))};
g.k.hide=function(){this.isActive&&(g.yp(this.Ib(),"iv-promo-inactive"),this.isActive=!1,this.Ib().setAttribute("aria-hidden","true"))};
g.k.UN=function(a,b,c,d,e,f){return this.isCollapsed?!1:m3.prototype.UN.call(this,a,b,c,d,e,f)};
g.k.k$=function(a){this.V=!0;agb(this,500,a)};
g.k.j$=function(){this.V=!1;bgb(this)};
g.k.e$=function(a){a.stopPropagation();this.hide()};
g.k.f$=function(a){a.stopPropagation();cgb(this);this.isCollapsed=!0;g.yp(this.Ib(),"iv-promo-collapsed-no-delay");this.G.start()};
g.k.destroy=function(){this.G.dispose();m3.prototype.destroy.call(this)};g.z(egb,g.YX);g.k=egb.prototype;g.k.oi=function(a,b){if(!tgb(this.player.U().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.d1(b))&&jgb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(Ifb(this.j,b),I2(this.player)),!0}return null};
g.k.getOptions=function(){return tgb(this.player.U().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Tv=function(){var a=this.player.U(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return g.JR(b)||this.player.isMutedByEmbedsMutedAutoplay()?!1:c===1&&!b.t4||a.Ja.get(b.videoId)||g.AR(b)||g.tMa(b)?!0:!1};
g.k.nM=function(){if(this.C){var a=this.player.ob().getVideoContentRect(!0);g.Nm(this.C.element,a.width,a.height);g.Jm(this.C.element,a.left,a.top)}if(this.j){var b=this.player.Ko();a=this.j;b=b.width;g.Cp(a.D,"iv-drawer-small",b<=426);g.Cp(a.D,"iv-drawer-big",b>=1280)}};
g.k.e5=function(a){ggb(this,a.state);g.U(a.state,2)&&(this.Ll()&&this.Zp()&&this.player.getPresentingPlayerType()!==2&&this.KC(!1),this.JC(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.Fr(h)&&h.responseXML?h.responseXML:null)&&(jgb(b,h),g.yp(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.YX.prototype.load.call(this);ggb(this,this.player.getPlayerStateObject());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.tt()&&(a=kgb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.U().Ja.get(d);f&&lgb(e,f);f=f&&(f.jP||f.GJ);if(!c.Jw||f)c.Xa?hgb(this,c.Xa,e):(this.T=function(){if(!b.V)b.onVideoDataChange(e);var h=b.player.getVideoData();(h==null?0:g.zR(h))&&!b.oa&&pgb(b,h)},this.player.addEventListener("videodatachange",this.T));
g.jS(this.player,this.C.element,4);this.nM();(f=g.AR(c))&&ogb(this,f);(f=g.tMa(c))&&f.featuredChannel&&sgb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.qh=g.hh("ytp-cards-button",this.player.getRootNode());g.zR(c)&&pgb(this,c)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Xa&&hgb(this,b.Xa,a)};
g.k.unload=function(){this.player.Ze("annotations_module");for(var a=g.w(Object.keys(this.K)),b=a.next();!b.done;b=a.next())this.K[b.value].destroy();this.X=null;this.j&&(this.j.destroy(),this.j=null,I2(this.player));this.V=!1;this.G&&(this.G.abort(),this.G=null);this.oa=!1;this.K={};this.B.hide();g.YX.prototype.unload.call(this);this.C.detach();this.T&&(this.player.removeEventListener("videodatachange",this.T),this.T=null)};
g.k.l1=function(a){a===this.player.getVideoData().videoId&&(this.loaded?mgb(this):this.load())};
g.k.Ll=function(){var a;return((a=this.j)==null?void 0:a.isAvailable())||this.oa};
g.k.Zp=function(){return!!this.j&&this.j.C};
g.k.KC=function(a,b,c){b=b===void 0?!1:b;this.Ll();this.j&&(a?c?f3(this.j,c,b):f3(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):g3(this.j))};
g.k.JC=function(a,b){this.player.publish(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.va=function(){this.player.U().Ja.unsubscribe("vast_info_card_add",this.l1,this);g.Ap(this.player.getRootNode(),g.H_.IV_DRAWER_OPEN);for(var a=this.qa,b=g.jp,c=0,d=a.length;c<d;c++)b.Bk(a[c]);this.qa.length=0;g.YX.prototype.va.call(this)};
g.k.createElement=function(a){a=new g.S(a);g.P(this,a);return a.element};g.XX("annotations_module",egb);g.XX("creatorendscreen",afb);})(_yt_player);
